apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: mysql-cluster
