apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: exporter
        image: wrouesnel/postgres_exporter:v0.10.1
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DATA_SOURCE_URI
          value: "postgres://ruslank:MyPostgresPassword123!@postgres-primary:5432/django_app_db?sslmode=disable"
        ports:
        - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
