version: "3.8"

services:
  web:
    build: .
    container_name: film_library
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5001
