# Generated by Django 5.1.4 on 2024-12-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
