"""
5. Генератор для створення нескінченної послідовності.

Створіть генератор, який генерує нескінченну послідовність парних чисел.
Використайте менеджер контексту для обмеження кількості генерованих чисел до 100 і збереження їх у файл.
"""


def even_numbers():
    """Yield an infinite sequence of even numbers starting from 2."""
    number = 2
    while True:
        yield number
        number += 2


class LimitedGenerator:
    """
    Limit the number of values generated by a generator.

    :param generator: The generator to limit.
    :type generator: generator
    :param limit: The maximum number of values to generate.
    :type limit: int
    """
    def __init__(self, generator, limit):
        """
        Initialize a LimitedGenerator instance.

        :param generator: The generator to limit.
        :type generator: generator
        :param limit: The maximum number of values to generate.
        :type limit: int
        """
        self.generator = generator
        self.limit = limit

    def __enter__(self):
        """
        Enter the runtime context related to this object.

        Initialize the counter and return the instance.

        :return: The instance of LimitedGenerator.
        :rtype: LimitedGenerator
        """
        self.counter = 0
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """
        Exit the runtime context related to this object.

        It does not handle any exceptions.

        :param exc_type: The exception type.
        :param exc_val: The exception value.
        :param exc_tb: The traceback object.
        """
        pass

    def __iter__(self):
        """
        Yield values from the generator until the limit is reached.

        :return: Values from the generator up to the specified limit.
        :rtype: generator
        """
        for value in self.generator:
            if self.counter < self.limit:
                yield value
                self.counter += 1
            else:
                break


# Use LimitedGenerator to generate up to 100 even numbers and write them to a file
with LimitedGenerator(even_numbers(), 100) as limited_gen:
    with open('hw_05_05.txt', 'w') as file:
        for number in limited_gen:
            file.write(f"{number}\n")
