apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: k8s-space
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      nodePort: 30080
      targetPort: 8000
