apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: k8s-space
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'django'
        static_configs:
          - targets: ['django-service.k8s-space.svc.cluster.local:8000']
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres.k8s-space.svc.cluster.local:5432']
      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql.k8s-space.svc.cluster.local:3306']
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter.k8s-space.svc.cluster.local:9187']
      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['mysql-exporter.k8s-space.svc.cluster.local:9104']

