version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pet_diary_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: pet_diary_web_postgres
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  bot:
    build: .
    command: python manage.py bot
    environment:
      - TELEGRAM_BOT_TOKEN=123456:ABC...
    depends_on:
      - web
volumes:
  db_data:
