# Generated by Django 5.1.4 on 2025-01-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlclick',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urlclick',
            name='device_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
